version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .
    - requirements: requirements/requirements.docs.txt
