name: Release

on:
  push:
    tags: ["*"]

concurrency:
  group: {{ '${{ github.workflow }}-${{ github.head_ref || github.run_id }}' }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

permissions:
  contents: read  # read repository contents

jobs:
  build:
    name: Build Wheel and SDist
    runs-on: ubuntu-latest
    outputs:
      name: {{ '${{ steps.baipp.outputs.package_name }}' }}
      version: {{ '${{ steps.baipp.outputs.package_version }}' }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        persist-credentials: false
    - uses: hynek/build-and-inspect-python-package@f3d069d0f9a3c9169d1a483318bb0e09876a6fd6 # v2.15.0
      id: baipp

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Needed for OIDC PyPI publishing
    needs: [build]
    ## TODO: optionally provide the name of the environment for the trusted
    ## publisher on PyPI
    ## https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
    # environment:
    #   name: pypi
    #   url: https://pypi.org/project/{{ '${{ needs.build.outputs.name }}' }}/{{ '${{ needs.build.outputs.version }}' }}
    steps:
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: Packages
        path: dist
    - name: Publish
      ## TODO: create a trusted publisher on PyPI
      ## https://docs.pypi.org/trusted-publishers/
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
