### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test {{cookiecutter.target_id}}

on:
  push:
    branches: [main]
    paths:
    - .github/workflows/test.yml
    - {{ cookiecutter.library_name }}/**
    - tests/**
    - pyproject.toml
    - uv.lock
  pull_request:
    paths:
    - .github/workflows/test.yml
    - {{ cookiecutter.library_name }}/**
    - tests/**
    - pyproject.toml
    - uv.lock
  workflow_dispatch:

concurrency:
  group: {{ '${{ github.workflow }}-${{ github.head_ref || github.run_id }}' }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

permissions:
  contents: read  # read repository contents

jobs:
  build-package:
    name: Build & verify package
    runs-on: ubuntu-latest
    outputs:
      supported-python-versions: {{ '${{ steps.baipp.outputs.supported_python_classifiers_json_array }}' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: hynek/build-and-inspect-python-package@f3d069d0f9a3c9169d1a483318bb0e09876a6fd6 # v2.15.0
        id: baipp

  pytest:
    name: Test
    needs: [build-package]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: {{ '${{ fromJson(needs.build-package.outputs.supported-python-versions) }}' }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Setup uv
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
      with:
        python-version: {{ '${{ matrix.python-version }}' }}
    - name: Run Tox
      run: |
        uvx --with=tox-uv tox -e {{ '${{ matrix.python-version }}' }}

  typing:
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Setup uv
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
    - name: Run Tox
      run: >
        uvx
        --managed-python
        --with=tox-uv
        tox -e typing
