name: Bug Report
description: File a bug report
title: "bug: <title>"
type: Fix
assignees:
  - edgarrmondragon

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: sdk_version
    attributes:
      label: Singer SDK Version
      description: Version of the library you are using
      placeholder: "0.44.3"
    validations:
      required: true
  - type: checkboxes
    id: regression
    attributes:
      label: Is this a regression?
      description: Meaning this is something that previously worked correctly
      options:
        - label: "Yes"
  - type: dropdown
    id: python_version
    attributes:
      label: Python Version
      description: Version of Python you are using
      options:
        - "NA"
        - "3.13"
        - "3.12"
        - "3.11"
        - "3.10"
        - "3.9"
        - "3.8 or earlier"
    validations:
      required: true
  - type: dropdown
    id: scope
    attributes:
      label: Bug scope
      description: Functionality this bug affects
      options:
        - Taps (catalog, state, etc.)
        - Mapping (stream maps, flattening, etc.)
        - Targets (data type handling, batching, SQL object generation, etc.)
        - Configuration (settings parsing, validation, etc.)
        - CLI (options, error messages, logging, etc.)
        - Cookiecutter templates
        - Other
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system you are using
      placeholder: "Windows"
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: Describe what you were trying to get done, what you expected to happen, and what actually happened. Include any error messages you received, or a snippet of the code that caused the issue.
      placeholder: Tell us what happened, what went wrong, and what you expected to happen
    validations:
      required: true
  - type: input
    id: slack_or_linen
    attributes:
      label: Link to Slack/Linen
      description: Provide a link to the Slack or Linen conversation, if applicable
      placeholder: "https://..."
