name: Feature request
description: Request a new feature
title: "feat: <title>"
labels: ["kind/Feature", "valuestream/SDK"]
type: Feat
assignees:
  - edgarrmondragon

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new feature!
  - type: dropdown
    id: scope
    attributes:
      label: Feature scope
      description: Functionality this new feature would impact
      options:
        - Taps (catalog, state, tests, etc.)
        - Inline mapping (stream maps, flattening, etc.)
        - Targets (data type handling, batching, SQL object generation, tests, etc.)
        - Configuration (settings parsing, validation, etc.)
        - CLI (options, error messages, logging, etc.)
        - Cookiecutter templates
        - Other
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: Description
      description: Describe the feature you would like to see
    validations:
      required: true
