name: Feature request
description: Request a new feature
title: "[Feature]: <title>"
labels: ["kind/Feature", "valuestream/SDK"]
assignees:
  - meltano/engineering

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new feature!
  - type: dropdown
    id: scope
    attributes:
      label: Feature scope
      description: Functionality this new feature would impact
      options:
        - Taps (catalog, state, stream maps, etc.)
        - Targets (data type handling, batching, SQL object generation, etc.)
        - Configuration (settings parsing, validation, etc.)
        - CLI (options, error messages, logging, etc.)
        - Other
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: Description
      description: Describe the feature you would like to see
    validations:
      required: true
