[project]
name = "tap-csv"
version = "0.1.0"
description = "Singer tap for CSV files, built with the Meltano Singer SDK"
authors = [{ name = "Meltano Team", email = "hello@meltano.com" }]
keywords = [
    "ELT",
    "CSV",
    "Comma-separated values",
]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
license = "Apache-2.0"
requires-python = ">=3.9"
dependencies = [
    "singer-sdk~=0.48.1",
]

[project.scripts]
tap-csv = 'tap_csv.tap:TapCSV.cli'

[tool.mypy]
warn_unused_configs = true

[tool.uv.sources]
singer-sdk = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
