### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test {{cookiecutter.mapper_id}}

on:
  push:
    branches: [main]
    paths:
    - .github/workflows/test.yml
    - {{ cookiecutter.library_name }}/**
    - tests/**
    - pyproject.toml
    - uv.lock
  pull_request:
    paths:
    - .github/workflows/test.yml
    - {{ cookiecutter.library_name }}/**
    - tests/**
    - pyproject.toml
    - uv.lock
  workflow_dispatch:

concurrency:
  group: {{ '${{ github.workflow }}-${{ github.head_ref || github.run_id }}' }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  build-package:
    name: Build & verify package
    runs-on: ubuntu-latest
    outputs:
      supported-python-versions: {{ '${{ steps.baipp.outputs.supported_python_classifiers_json_array }}' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: hynek/build-and-inspect-python-package@efb823f52190ad02594531168b7a2d5790e66516 # v2.14.0
        id: baipp

  pytest:
    name: Integration
    needs: [build-package]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: {{ '${{ fromJson(needs.build-package.outputs.supported-python-versions) }}' }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Set up Python {{ '${{ matrix.python-version }}' }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: {{ '${{ matrix.python-version }}' }}
    - name: Setup uv
      uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
    - name: Run Tox
      run: |
        uvx --with=tox-uv tox -e {{ '${{ matrix.python-version }}' }}

  typing:
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: 3.x
    - name: Setup uv
      uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
    - name: Run Tox
      run: |
        uvx --with=tox-uv tox -e typing
