ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'
  skip:
  - uv-lock

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-json
    exclude: |
      (?x)^(
        .*/launch.json
      )$
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.33.3
  hooks:
  - id: check-dependabot
  - id: check-github-workflows
  - id: check-meltano

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.0
  hooks:
  - id: ruff-check
    args: [--diff]
  - id: ruff-format
    args: [--diff]

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.8.16
  hooks:
  - id: uv-lock
  - id: uv-sync
